#Site
title: Mishell blogs
description: Este es mi diario
logo: favicon.png
url: mishell0vando.com
rss_url: /feed.xml

# Jekyll
permalink:          /blog/:title/
markdown:           kramdown
highlighter:        rouge
kramdown:
  auto_ids:         true
  footnote_nr:      1
  entity_output:    as_char
  toc_levels:       1..6
  enable_coderay:   false
sass:
  sass_dir:         assets/_sass
  style:            compressed

# Comment
comment:
  disqus: Mishell0vando    
  # duoshuo: Mishell
  # youyan: 2122392
  # laibili: MTAyMC8yODgzNC81NDA0
  gitalk: true

# Website analytics
google_analytics: UA-82494501-1
baidu_analytics: 5b31ffbbdc6cff18727f3adf75a03777    #from //hm.baidu.com/hm.js?***

# Author information:
author:
  #resume: /resume
  name: Mishell      #tMyDays
  about_me: Hola, soy Mishell. Mi postre favorito es el Cheesecake y las gelatinas (especialmente las de uva y mosaico).
 
# Social Links
email:               ovandovaleri21@gmail.com
#twitter:            username
facebook:            Shell Ovando
github:              Mishell0vando
#instagram:          dearsshell
#pinterest:          baeee

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-gist

# Exclude list
exclude: [README.md, Gemfile, Gemfile.lock, _site, src, vendor, CNAME, LICENSE, Rakefile,.sass-cache,.DS_Store,.idea]


